services:
  postgres:
    image: postgres:16.4-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=imac
      - POSTGRES_PASSWORD=teste
      - POSTGRES_ATOMIC_REQUESTS=1
    # ports:
    #   - 5432:5432
    restart: always
  django:
    image: python:3.12.0-slim
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python manage.py runserver"

volumes:
  postgres-data: {}

networks:
  projJoao-intra: